import 'package:flutter/material.dart';
import 'package:flutterapp/veganicappapp/generatedlandingpagewidget/generated/GeneratedGroup1732Widget.dart';
import 'package:flutterapp/veganicappapp/generatedlandingpagewidget/generated/GeneratedFrame1Widget.dart';

/* Frame Landing page
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLandingpageWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 428.0,
        height: 800.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 152, 196, 61),
                ),
              ),
              Positioned(
                left: -22.0,
                top: -17.0,
                right: null,
                bottom: null,
                width: 483.0,
                height: 978.0,
                child: GeneratedGroup1732Widget(),
              ),
              Positioned(
                left: 64.0,
                top: 61.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 684.6817626953125,
                child: GeneratedFrame1Widget(),
              )
            ]),
      ),
    ));
  }
}
