import 'package:flutter/material.dart';
import 'package:flutterapp/veganicappapp/generateddescriptionofitemwidget/generated/Generated32arrowleftoutline11Widget1.dart';
import 'package:flutterapp/veganicappapp/generateddescriptionofitemwidget/generated/GeneratedGroup1730Widget.dart';
import 'package:flutterapp/veganicappapp/generateddescriptionofitemwidget/generated/GeneratedRectangle2Widget1.dart';
import 'package:flutterapp/veganicappapp/generateddescriptionofitemwidget/generated/GeneratedGroup1737Widget.dart';
import 'package:flutterapp/veganicappapp/generateddescriptionofitemwidget/generated/GeneratedGroup14Widget.dart';
import 'package:flutterapp/veganicappapp/generateddescriptionofitemwidget/generated/GeneratedOurfriedriceismadefromthefinestingredientsandveggiessin.dart';
import 'package:flutterapp/veganicappapp/generateddescriptionofitemwidget/generated/GeneratedIstockphoto672810138612x612Widget.dart';
import 'package:flutterapp/veganicappapp/generateddescriptionofitemwidget/generated/GeneratedK95Widget.dart';
import 'package:flutterapp/veganicappapp/generateddescriptionofitemwidget/generated/GeneratedGroup1725Widget1.dart';
import 'package:flutterapp/veganicappapp/generateddescriptionofitemwidget/generated/GeneratedEllipse2Widget2.dart';
import 'package:flutterapp/veganicappapp/generateddescriptionofitemwidget/generated/GeneratedAdditionsWidget.dart';
import 'package:flutterapp/veganicappapp/generateddescriptionofitemwidget/generated/GeneratedGroup1729Widget.dart';
import 'package:flutterapp/veganicappapp/generateddescriptionofitemwidget/generated/GeneratedRectangle115Widget.dart';
import 'package:flutterapp/veganicappapp/generateddescriptionofitemwidget/generated/GeneratedGroupWidget7.dart';
import 'package:flutterapp/veganicappapp/generateddescriptionofitemwidget/generated/GeneratedDescriptionWidget.dart';
import 'package:flutterapp/veganicappapp/generateddescriptionofitemwidget/generated/GeneratedK95Widget1.dart';
import 'package:flutterapp/veganicappapp/generateddescriptionofitemwidget/generated/GeneratedEllipse3Widget2.dart';
import 'package:flutterapp/veganicappapp/generateddescriptionofitemwidget/generated/GeneratedEllipse4Widget2.dart';
import 'package:flutterapp/veganicappapp/generateddescriptionofitemwidget/generated/GeneratedGroup46Widget.dart';
import 'package:flutterapp/veganicappapp/generateddescriptionofitemwidget/generated/GeneratedGroup1716Widget.dart';
import 'package:flutterapp/veganicappapp/generateddescriptionofitemwidget/generated/GeneratedGroup43Widget.dart';
import 'package:flutterapp/veganicappapp/generateddescriptionofitemwidget/generated/GeneratedTomatoesWidget.dart';

/* Frame Description of item
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDescriptionofitemWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(50.0),
      child: Container(
        width: 428.0,
        height: 800.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(50.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(50.0),
                child: Container(
                  color: Color.fromARGB(255, 152, 196, 61),
                ),
              ),
              Positioned(
                left: 444.371826171875,
                top: 296.0000305175781,
                right: null,
                bottom: null,
                width: 450.0,
                height: 343.186767578125,
                child: GeneratedIstockphoto672810138612x612Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 255.0,
                right: null,
                bottom: null,
                width: 428.0,
                height: 545.0,
                child: GeneratedRectangle2Widget1(),
              ),
              Positioned(
                left: -14.0,
                top: -11.0,
                right: null,
                bottom: null,
                width: 70.0,
                height: 70.0,
                child: GeneratedEllipse3Widget2(),
              ),
              Positioned(
                left: 239.0,
                top: 26.0,
                right: null,
                bottom: null,
                width: 13.0,
                height: 13.0,
                child: GeneratedEllipse2Widget2(),
              ),
              Positioned(
                left: 409.0,
                top: 109.0,
                right: null,
                bottom: null,
                width: 70.0,
                height: 70.0,
                child: GeneratedEllipse4Widget2(),
              ),
              Positioned(
                left: 54.0,
                top: 649.0,
                right: null,
                bottom: null,
                width: 321.0,
                height: 51.0,
                child: GeneratedGroup1737Widget(),
              ),
              Positioned(
                left: 23.0,
                top: 239.0,
                right: null,
                bottom: null,
                width: 171.0,
                height: 51.0,
                child: GeneratedGroup1729Widget(),
              ),
              Positioned(
                left: 344.0,
                top: 241.49893188476562,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedGroup43Widget(),
              ),
              Positioned(
                left: 30.0,
                top: 322.0,
                right: null,
                bottom: null,
                width: 158.0,
                height: 42.0,
                child: GeneratedDescriptionWidget(),
              ),
              Positioned(
                left: 30.0,
                top: 351.0,
                right: null,
                bottom: null,
                width: 181.0,
                height: 86.0,
                child:
                    GeneratedOurfriedriceismadefromthefinestingredientsandveggiessin(),
              ),
              Positioned(
                left: 239.0,
                top: 323.0,
                right: null,
                bottom: null,
                width: 161.0,
                height: 122.0,
                child: GeneratedGroup1730Widget(),
              ),
              Positioned(
                left: 39.0,
                top: 443.0,
                right: null,
                bottom: null,
                width: 350.0,
                height: 78.0,
                child: GeneratedGroup1716Widget(),
              ),
              Positioned(
                left: 40.1070556640625,
                top: 619.0,
                right: null,
                bottom: null,
                width: 43.89299011230469,
                height: 23.0,
                child: GeneratedK95Widget(),
              ),
              Positioned(
                left: 34.0,
                top: 568.0,
                right: null,
                bottom: null,
                width: 361.0,
                height: 29.0,
                child: GeneratedRectangle115Widget(),
              ),
              Positioned(
                left: 375.0,
                top: 586.4453735351562,
                right: null,
                bottom: null,
                width: 13.0,
                height: 6.523193359375,
                child: GeneratedGroupWidget7(),
              ),
              Positioned(
                left: 54.0,
                top: 577.0,
                right: null,
                bottom: null,
                width: 70.0,
                height: 20.0,
                child: GeneratedTomatoesWidget(),
              ),
              Positioned(
                left: 46.0,
                top: 542.0,
                right: null,
                bottom: null,
                width: 157.0,
                height: 38.0,
                child: GeneratedAdditionsWidget(),
              ),
              Positioned(
                left: 188.0,
                top: 617.0,
                right: null,
                bottom: null,
                width: 52.0,
                height: 20.0,
                child: GeneratedGroup46Widget(),
              ),
              Positioned(
                left: 363.21923828125,
                top: 610.0,
                right: null,
                bottom: null,
                width: 31.849315643310547,
                height: 31.0,
                child: GeneratedGroup14Widget(),
              ),
              Positioned(
                left: 2.0,
                top: 714.0,
                right: null,
                bottom: null,
                width: 428.0,
                height: 86.0,
                child: GeneratedGroup1725Widget1(),
              ),
              Positioned(
                left: 12.0,
                top: 293.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: Generated32arrowleftoutline11Widget1(),
              ),
              Positioned(
                left: 347.0,
                top: 276.0,
                right: null,
                bottom: null,
                width: 68.0,
                height: 45.0,
                child: GeneratedK95Widget1(),
              )
            ]),
      ),
    ));
  }
}
