import 'package:flutter/material.dart';
import 'package:flutterapp/veganicappapp/generatedcheckoutwidget/generated/GeneratedEllipse3Widget5.dart';
import 'package:flutterapp/veganicappapp/generatedcheckoutwidget/generated/GeneratedHiUserWidget2.dart';
import 'package:flutterapp/veganicappapp/generatedcheckoutwidget/generated/GeneratedEllipse4Widget4.dart';
import 'package:flutterapp/veganicappapp/generatedcheckoutwidget/generated/GeneratedGroup1739Widget.dart';
import 'package:flutterapp/veganicappapp/generatedcheckoutwidget/generated/GeneratedPaymentWidget.dart';
import 'package:flutterapp/veganicappapp/generatedcheckoutwidget/generated/GeneratedWhatwouldyouliketoordertodayWidget2.dart';
import 'package:flutterapp/veganicappapp/generatedcheckoutwidget/generated/GeneratedFemaleavatarandcirclesvgrepocom1Widget2.dart';
import 'package:flutterapp/veganicappapp/generatedcheckoutwidget/generated/Generated32arrowleftoutline11Widget3.dart';
import 'package:flutterapp/veganicappapp/generatedcheckoutwidget/generated/GeneratedEllipse2Widget7.dart';
import 'package:flutterapp/veganicappapp/generatedcheckoutwidget/generated/GeneratedRectangle2Widget3.dart';
import 'package:flutterapp/veganicappapp/generatedcheckoutwidget/generated/GeneratedGroup1738Widget.dart';
import 'package:flutterapp/veganicappapp/generatedcheckoutwidget/generated/GeneratedGroup1725Widget3.dart';

/* Frame Checkout
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCheckoutWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 428.0,
        height: 800.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 152, 196, 61),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 188.0,
                right: null,
                bottom: null,
                width: 428.0,
                height: 615.0,
                child: GeneratedRectangle2Widget3(),
              ),
              Positioned(
                left: 0.0,
                top: 840.0,
                right: null,
                bottom: null,
                width: 428.0,
                height: 86.0,
                child: GeneratedGroup1725Widget3(),
              ),
              Positioned(
                left: 22.0,
                top: 84.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 35.0,
                child: GeneratedFemaleavatarandcirclesvgrepocom1Widget2(),
              ),
              Positioned(
                left: -14.0,
                top: -11.0,
                right: null,
                bottom: null,
                width: 70.0,
                height: 70.0,
                child: GeneratedEllipse3Widget5(),
              ),
              Positioned(
                left: 239.0,
                top: 26.0,
                right: null,
                bottom: null,
                width: 13.0,
                height: 13.0,
                child: GeneratedEllipse2Widget7(),
              ),
              Positioned(
                left: 409.0,
                top: 109.0,
                right: null,
                bottom: null,
                width: 70.0,
                height: 70.0,
                child: GeneratedEllipse4Widget4(),
              ),
              Positioned(
                left: 80.0,
                top: 90.0,
                right: null,
                bottom: null,
                width: 52.0,
                height: 20.0,
                child: GeneratedHiUserWidget2(),
              ),
              Positioned(
                left: 80.0,
                top: 120.0,
                right: null,
                bottom: null,
                width: 241.0,
                height: 20.0,
                child: GeneratedWhatwouldyouliketoordertodayWidget2(),
              ),
              Positioned(
                left: 54.0,
                top: 646.0,
                right: null,
                bottom: null,
                width: 321.0,
                height: 51.0,
                child: GeneratedGroup1738Widget(),
              ),
              Positioned(
                left: 34.0,
                top: 211.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: Generated32arrowleftoutline11Widget3(),
              ),
              Positioned(
                left: 160.0,
                top: 215.0,
                right: null,
                bottom: null,
                width: 96.0,
                height: 29.0,
                child: GeneratedPaymentWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 275.0,
                right: null,
                bottom: null,
                width: 428.0,
                height: 525.0,
                child: GeneratedGroup1739Widget(),
              )
            ]),
      ),
    ));
  }
}
