import 'package:flutter/material.dart';
import 'package:flutterapp/veganicappapp/generatedqrscannerwidget/generated/GeneratedWhatwouldyouliketoordertodayWidget.dart';
import 'package:flutterapp/veganicappapp/generatedqrscannerwidget/generated/GeneratedEllipse2Widget1.dart';
import 'package:flutterapp/veganicappapp/generatedqrscannerwidget/generated/GeneratedGroup1725Widget.dart';
import 'package:flutterapp/veganicappapp/generatedqrscannerwidget/generated/backbutton.dart';
import 'package:flutterapp/veganicappapp/generatedqrscannerwidget/generated/GeneratedEllipse3Widget1.dart';
import 'package:flutterapp/veganicappapp/generatedqrscannerwidget/generated/GeneratedRectangle1059Widget.dart';
import 'package:flutterapp/veganicappapp/generatedqrscannerwidget/generated/GeneratedScanQRcodetoproceedwiththetransactionWidget.dart';
import 'package:flutterapp/veganicappapp/generatedqrscannerwidget/generated/GeneratedEllipse4Widget1.dart';
import 'package:flutterapp/veganicappapp/generatedqrscannerwidget/generated/GeneratedFemaleavatarandcirclesvgrepocom1Widget.dart';
import 'package:flutterapp/veganicappapp/generatedqrscannerwidget/generated/Generated2192199050_vegfriedricepngtransparentpng1Widget.dart';
import 'package:flutterapp/veganicappapp/generatedqrscannerwidget/generated/GeneratedGroup5Widget.dart';
import 'package:flutterapp/veganicappapp/generatedqrscannerwidget/generated/GeneratedGroup1733Widget.dart';
import 'package:flutterapp/veganicappapp/generatedqrscannerwidget/generated/GeneratedRectangle3Widget.dart';
import 'package:flutterapp/veganicappapp/generatedqrscannerwidget/generated/GeneratedRectangle2Widget.dart';
import 'package:flutterapp/veganicappapp/generatedqrscannerwidget/generated/GeneratedHiUserWidget.dart';
import 'package:flutterapp/veganicappapp/generatedqrscannerwidget/generated/GeneratedProceedtopayWidget.dart';

/* Frame QR Scanner
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedQRScannerWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 428.0,
        height: 800.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 152, 196, 61),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 200.0,
                right: null,
                bottom: null,
                width: 428.0,
                height: 601.0,
                child: GeneratedRectangle2Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 714.0,
                right: null,
                bottom: null,
                width: 428.0,
                height: 86.0,
                child: GeneratedGroup1725Widget(),
              ),
              Positioned(
                left: 22.0,
                top: 84.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 35.0,
                child: GeneratedFemaleavatarandcirclesvgrepocom1Widget(),
              ),
              Positioned(
                left: -14.0,
                top: -11.0,
                right: null,
                bottom: null,
                width: 70.0,
                height: 70.0,
                child: GeneratedEllipse3Widget1(),
              ),
              Positioned(
                left: 239.0,
                top: 26.0,
                right: null,
                bottom: null,
                width: 13.0,
                height: 13.0,
                child: GeneratedEllipse2Widget1(),
              ),
              Positioned(
                left: 409.0,
                top: 109.0,
                right: null,
                bottom: null,
                width: 70.0,
                height: 70.0,
                child: GeneratedEllipse4Widget1(),
              ),
              Positioned(
                left: 80.0,
                top: 90.0,
                right: null,
                bottom: null,
                width: 52.0,
                height: 20.0,
                child: GeneratedHiUserWidget(),
              ),
              Positioned(
                left: 80.0,
                top: 120.0,
                right: null,
                bottom: null,
                width: 241.0,
                height: 20.0,
                child: GeneratedWhatwouldyouliketoordertodayWidget(),
              ),
              Positioned(
                left: 54.0,
                top: 640.0,
                right: null,
                bottom: null,
                width: 321.0,
                height: 51.0,
                child: GeneratedRectangle3Widget(),
              ),
              Positioned(
                left: 157.0,
                top: 657.0,
                right: null,
                bottom: null,
                width: 116.0,
                height: 20.0,
                child: GeneratedProceedtopayWidget(),
              ),
              Positioned(
                left: 34.0,
                top: 255.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: Generated32arrowleftoutline11Widget(),
              ),
              Positioned(
                left: 85.0,
                top: 255.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 38.0,
                child: GeneratedScanQRcodetoproceedwiththetransactionWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 310.0,
                right: null,
                bottom: null,
                width: 428.0,
                height: 316.0,
                child: GeneratedRectangle1059Widget(),
              ),
              Positioned(
                left: 92.0,
                top: 347.0,
                right: null,
                bottom: null,
                width: 238.0,
                height: 238.0,
                child: GeneratedGroup1733Widget(),
              ),
              Positioned(
                left: 113.0,
                top: 389.0,
                right: null,
                bottom: null,
                width: 196.0,
                height: 161.0,
                child:
                    Generated2192199050_vegfriedricepngtransparentpng1Widget(),
              ),
              Positioned(
                left: 186.0,
                top: 485.0,
                right: null,
                bottom: null,
                width: 44.0,
                height: 31.982757568359375,
                child: GeneratedGroup5Widget(),
              )
            ]),
      ),
    ));
  }
}
