import 'package:flutter/material.dart';
import 'package:flutterapp/veganicappapp/generatedbasketwidget/generated/GeneratedEllipse3Widget4.dart';
import 'package:flutterapp/veganicappapp/generatedbasketwidget/generated/GeneratedMybasketWidget.dart';
import 'package:flutterapp/veganicappapp/generatedbasketwidget/generated/GeneratedGroup1728Widget.dart';
import 'package:flutterapp/veganicappapp/generatedbasketwidget/generated/GeneratedEllipse4Widget3.dart';
import 'package:flutterapp/veganicappapp/generatedbasketwidget/generated/GeneratedFemaleavatarandcirclesvgrepocom1Widget1.dart';
import 'package:flutterapp/veganicappapp/generatedbasketwidget/generated/GeneratedCompleteOrderWidget.dart';
import 'package:flutterapp/veganicappapp/generatedbasketwidget/generated/GeneratedEllipse2Widget3.dart';
import 'package:flutterapp/veganicappapp/generatedbasketwidget/generated/GeneratedRectangle2Widget2.dart';
import 'package:flutterapp/veganicappapp/generatedbasketwidget/generated/GeneratedGroup1725Widget2.dart';
import 'package:flutterapp/veganicappapp/generatedbasketwidget/generated/GeneratedGroup51Widget.dart';
import 'package:flutterapp/veganicappapp/generatedbasketwidget/generated/GeneratedHiUserWidget1.dart';
import 'package:flutterapp/veganicappapp/generatedbasketwidget/generated/GeneratedWhatwouldyouliketoordertodayWidget1.dart';
import 'package:flutterapp/veganicappapp/generatedbasketwidget/generated/GeneratedRectangle3Widget2.dart';
import 'package:flutterapp/veganicappapp/generatedbasketwidget/generated/Generated32arrowleftoutline11Widget2.dart';
import 'package:flutterapp/veganicappapp/generatedbasketwidget/generated/GeneratedGroup1727Widget.dart';
import 'package:flutterapp/veganicappapp/generatedbasketwidget/generated/GeneratedGroup1735Widget.dart';
import 'package:flutterapp/veganicappapp/generatedbasketwidget/generated/GeneratedGroup68Widget.dart';
import 'package:flutterapp/veganicappapp/generatedbasketwidget/generated/GeneratedGroup1726Widget.dart';
import 'package:flutterapp/veganicappapp/generatedbasketwidget/generated/GeneratedK145Widget1.dart';

/* Frame Basket
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedBasketWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 428.0,
        height: 800.0,
        child: Stack(
            clipBehavior: Clip.none, fit: StackFit.expand,
            alignment: Alignment.center,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 152, 196, 61),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 188.0,
                right: null,
                bottom: null,
                width: 428.0,
                height: 612.0,
                child: GeneratedRectangle2Widget2(),
              ),
              Positioned(
                left: -1.0,
                top: 714.0,
                right: null,
                bottom: null,
                width: 428.0,
                height: 86.0,
                child: GeneratedGroup1725Widget2(),
              ),
              Positioned(
                left: 22.0,
                top: 84.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 35.0,
                child: GeneratedFemaleavatarandcirclesvgrepocom1Widget1(),
              ),
              Positioned(
                left: -14.0,
                top: -11.0,
                right: null,
                bottom: null,
                width: 70.0,
                height: 70.0,
                child: GeneratedEllipse3Widget4(),
              ),
              Positioned(
                left: 239.0,
                top: 26.0,
                right: null,
                bottom: null,
                width: 13.0,
                height: 13.0,
                child: GeneratedEllipse2Widget3(),
              ),
              Positioned(
                left: 409.0,
                top: 109.0,
                right: null,
                bottom: null,
                width: 70.0,
                height: 70.0,
                child: GeneratedEllipse4Widget3(),
              ),
              Positioned(
                left: 80.0,
                top: 90.0,
                right: null,
                bottom: null,
                width: 52.0,
                height: 20.0,
                child: GeneratedHiUserWidget1(),
              ),
              Positioned(
                left: 80.0,
                top: 120.0,
                right: null,
                bottom: null,
                width: 241.0,
                height: 20.0,
                child: GeneratedWhatwouldyouliketoordertodayWidget1(),
              ),
              Positioned(
                left: 11.0,
                top: 370.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 102.0,
                child: GeneratedGroup68Widget(),
              ),
              Positioned(
                left: 54.0,
                top: 648.0,
                right: null,
                bottom: null,
                width: 321.0,
                height: 51.0,
                child: GeneratedRectangle3Widget2(),
              ),
              Positioned(
                left: 154.0,
                top: 665.0,
                right: null,
                bottom: null,
                width: 123.0,
                height: 20.0,
                child: GeneratedCompleteOrderWidget(),
              ),
              Positioned(
                left: 14.0,
                top: 477.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 102.0,
                child: GeneratedGroup1726Widget(),
              ),
              Positioned(
                left: 163.0,
                top: 215.0,
                right: null,
                bottom: null,
                width: 91.0,
                height: 22.0,
                child: GeneratedMybasketWidget(),
              ),
              Positioned(
                left: 34.0,
                top: 211.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: Generated32arrowleftoutline11Widget2(),
              ),
              Positioned(
                left: 14.0,
                top: 255.0,
                right: null,
                bottom: null,
                width: 379.0,
                height: 109.0,
                child: GeneratedGroup1735Widget(),
              ),
              Positioned(
                left: 338.0,
                top: 399.0,
                right: null,
                bottom: null,
                width: 52.0,
                height: 20.0,
                child: GeneratedGroup1727Widget(),
              ),
              Positioned(
                left: 341.0,
                top: 502.0,
                right: null,
                bottom: null,
                width: 52.0,
                height: 20.0,
                child: GeneratedGroup1728Widget(),
              ),
              Positioned(
                left: 79.0,
                top: 594.0,
                right: null,
                bottom: null,
                width: 278.0,
                height: 19.0,
                child: GeneratedGroup51Widget(),
              ),
              Positioned(
                left: 323.0,
                top: 201.0,
                right: null,
                bottom: null,
                width: 83.0,
                height: 45.0,
                child: GeneratedK145Widget1(),
              )
            ]),
      ),
    ));
  }
}
